export const EventsDB = [
  {
    img: "img/eventpics/chitrakala.png",
    registerUrl: "https://forms.gle/YjfMvzaz596CGFLZ7",
    title: "Art Competition",
    description:
      "Welcome to the Genesis Art Club's Inter-Institute Art Competition! - 𝐂𝐡𝐢𝐭𝐫𝐚𝐤𝐚𝐥𝐚 Unleash your creativity as you bring the given themes to life on canvas. Join fellow artists in this vibrant celebration of art, where your masterpiece could be the highlight of the event! Let your imagination run wild and paint your way to artistic glory in our institute's informal art contest. Get ready for a brush with brilliance!",
    startDate: "26 Jan",
    endDate: "2 Feb",
    rules: [
      "Rule 1: Participants in the offline mode of participation will be given a standard A3 size sheet after the successful registration of each.",
      "Rule 2: Participants in online mode will have to submit their entries in the size of a sheet corresponding to the same aspect ratio of the A3 sheet.",
      "Rule 3: In case of plagiarism with regards to submission in both modes of participation, the entry will be disqualified, and organizers are not bound to notify the participant of his/her entry’s status.",
      "Rule 4: By submitting the entry, the participant agrees that his/her artwork can be posted on Genesis Art Club’s Instagram handle (@genesis_iiitvicd).",
      "Rule 5: In case of any dispute concerning the team and the competition’s rules and regulations, the decision taken by the organizers will be final and binding.",
    ],
    regdate: "26 Jan",
    organizers1: "Nimbalkar Siddarth",
    organizers1Photo: "img/clubpics/Siddhart.jpg",
    organizers2: "Bhargav Gugulothu",
    organizers2Photo: "img/cultpics/Bhargav.jpg",
  },
  {
    img: "img/eventpics/digitoons.png",
    registerUrl: "https://forms.gle/4Bf1H61Ahhu7rS3Y9",
    title: "Digital Cartooning",
    description:
      "Welcome to our electrifying online cartoon and comic-based painting event! - 𝐃𝐢𝐠𝐢𝐓𝐨𝐨𝐧𝐬🖌 Unleash your creativity using graphic design software, tablets, or any digital wizardry a0t your disposal. Dive into a world where talent and skill meets artistry as you craft original cartoons and dynamic comic strips. Join us for an inter-institute showdown of wit and imagination in this virtual art extravaganza! Let your artistic prowess shine and make this contest a canvas of laughter and innovation. Get ready to turn pixels into masterpieces!.",
    startDate: "26 Jan",
    endDate: "2 Feb",
    rules: [
      "Rule 1: All the students of IIITV-ICD are bound to participate in online mode only.",
      "Rule 2: Participants will be disqualified if their artwork consists of anything non-friendly or vulgar.",
      "Rule 3: Participants will have to submit either a pdf or jpg file consisting of their artwork.",
      "Rule 4: In case of plagiarism with regards to submission in both modes of participation, the entry will be disqualified, and organizers are not bound to notify the participant of his/her entry’s status.",
      "Rule 5: By submitting the entry, the participant agrees that his/her artwork can be posted on Genesis Art Club’s Instagram handle (@genesis_iiitvicd).",
      "Rule 6: In case of any dispute concerning the team and the competition’s rules and regulations, the decision taken by the organizers will be final and binding.",
    ],
    regdate: "26 Jan",
    organizers1: "Nimbalkar Siddarth",
    organizers1Photo: "img/clubpics/Siddhart.jpg",
    organizers2: "Bhargav Gugulothu",
    organizers2Photo: "img/cultpics/Bhargav.jpg",
  },
  {
    img: "img/eventpics/What If (30 x 36 in).png",
    registerUrl: "https://forms.gle/wPSJiRtoXosSmpbu7",
    title: "What If (Group Skit)",
    description:
      "Get ready for a night of theatrical magic with Eloquence Drama Club! Join us in an exciting role reversal challenge where teams of three perform as characters opposite to their real selves.",
    startDate: "27 Jan",
    endDate: "31 Jan",
    rules: [
      "Rule 1: Participants should form a team of 3 members.",
      "Rule 2: This event will consist of two rounds.",
      "Rule 3: In the first round, each team will be provided with a set of characters. The challenge is to transform these characters entirely and perform based on the altered roles.",
      "Rule 4: In the second round, teams will assign a Hindi proverb to a member of an opposing team. The chosen member must then act out the proverb, and their team members will attempt to guess it.",
      "Rule 5: Participants should maintain decorum; no vulgar actions will be entertained. Teams will immediately be disqualified, and no further participation will be encouraged.",
      "Rule 6: If a participant's action raises suspicion for the organizers, their candidature can be questioned. The organizers can take such decisions to ensure a fair competition.",
      "Rule 7: In case of any dispute regarding the team and competition's rules and regulations, the decision taken by the organizers will be final and binding.",
    ],
    regdate: "26 Jan",
    organizers1: "Ajay Deep",
    organizers1Photo: "img/clubpics/Ajay.jpg",
    organizers2: "Suryansh Singh Raghuvansh",
    organizers2Photo: "img/cultpics/Suryansh.png",
  },
  {
    img: "img/eventpics/Bollywood Quiz (30 x 36 in).png",
    registerUrl: "https://forms.gle/nJFkVkSVPFWYbi8U7",
    title: "Bollywood Quiz",
    description:
      "Dive into the glitz and glamour of Bollywood at our Quiz Event! Test your filmy knowledge and dance your way to fabulous prizes join us for a fun and entertaining quiz !",
    startDate: "27 Jan",
    endDate: "28 Jan",
    rules: [
      "Rule 1: The participant has to be a student of IIITV-ICD.",
      "Rule 2: Participants will have to register as a team of two through the circulated Google form. Only one person needs to fill out the form.",
      "Rule 3: Team name must be changed if the committee requests the participants to do so, or the participation will be nullified.",
      "Rule 4: The quiz will be conducted in two rounds.",
      "Rule 5: The top 10 teams will be contesting in the final round.",
      "Rule 6: Rules for the respective rounds will be communicated before the commencement of each round.",
      "Rule 7: Winners will be decided based on the score of the quiz.",
      "Rule 8: In case of unavailability of a team member, due to any reasons whatsoever, the team will be disqualified.",
      "Rule 9: If a student willing to participate cannot find a team member, they can approach the organizers for help.",
      "Rule 10: If a participant's action raises suspicion for the organizers, their candidature can be questioned. The organizers can take such decisions to ensure a fair competition.",
      "Rule 11: In case of any dispute regarding the team and competition's rules and regulations, the decision taken by the organizers will be final and binding.",
    ],
    regdate: "26 Jan",
    organizers1: "Ajay Deep",
    organizers1Photo: "img/clubpics/Ajay.jpg",
    organizers2: "Suryansh Singh Raghuvansh",
    organizers2Photo: "img/cultpics/Suryansh.png",
  },
  {
    img: "img/eventpics/NRITYAKALA (30 x 36 in).png",
    registerUrl:
      "https://docs.google.com/forms/d/e/1FAIpQLSejGb4G2mGQCemFLsq3Erijy0y-J2uCNHw714OVXn4TRcK-qw/viewform?usp=sf_link",
    title: "Nrityakala",
    description:
      "Step into the mesmerizing world of Bollywood at our Nrityakala dance event! Experience the allure of vibrant dance performances, immerse yourself in the enchanting choreography, and sway to the rhythm of a night filled with dazzling moves. Join us for an evening of captivating dance, unforgettable moments, and the sheer joy of movement!",
    startDate: "28 Jan",
    rules: [
      "Rule 1: Each participant or group is allotted a minimum performance time of 3 minutes.",
      "Rule 2: The event will take place on a well-equipped stage with high-quality audio equipment.",
      "Rule 3: Participants are encouraged to bring their unique artistic interpretations to the freestyle theme.",
      "Rule 4: Group should be maximum of five and minimum of three.",
    ],
    regdate: "26 Jan",
    organizers1: "Sumedha Baghmar",
    organizers1Photo: "img/clubpics/Sumedha.jpg",
    organizers2: "Diya Bhati",
    organizers2Photo: "img/cultpics/Diya.jpg",
  },
  {
    img: "img/eventpics/Photography Workshop (30 x 36 in).png",
    registerUrl: "https://forms.gle/9AgPZGJPp2j1xPNy9",
    title: "Photography contest",
    description:
      "Unlock creativity at Fest Pixellence 2.0! Capture the essence of diverse themes through your lens. Join this photography event, where images speak volumes, and visual storytelling takes center stage. Embrace the art of pixels!",
    startDate: "26 Jan",
    endDate: "2 Feb",
    rules: [
      "Rule 1: The contest will be a single-round online inter–institute event.",
      "Rule 2: The Photography Competition will have two prize pools, one exclusively for IIITV* students.",
      "Rule 3: Entries for IIITV* students will fall under an exclusive prize pool, and a separate prize will be awarded for all other entries.",
      "Rule 4: Entries are to be submitted along with the images under appropriate titles and a brief description/caption (motive) of the image.",
      "Rule 5: Each participant can submit a maximum of two entries.",
      "Rule 6: Entries will be accepted through Google Form only.",
      "Rule 7: The winners will be awarded certificates and prizes.",
      "Rule 8: Settings like Camera, Lens, Aperture, ISO, Shutter Speed, etc. should be mentioned on the Google form if used in manual mode.",
      "Rule 9: The name of the device used (Camera + lens(if used) / Phone Camera) is to be specified along with the entry.",
      "Rule 10: Basic Editing (like Contrast, Brightness, White Balance, Saturation, etc.) is permissible.",
      "Rule 11: Watermarking the image is optional.",
      "Rule 12: Brushing tools are not allowed.",
      "Rule 13: Theme-based entry is mandatory. If the entry fails to abide by the theme, it will be disqualified.",
      "Rule 14: Images that are found to be plagiarized will be disqualified immediately, and organizers are not bound to notify the participant.",
      "Rule 15: By submitting the entry, the participant agrees that his/her artwork can be posted on Capture Photography Club’s Instagram handle (@capture_iiitvicd).",
      "Rule 16: In case of any dispute, the decision of the judge and the organizers will be final and binding.",
      "Rule 17: Marking scheme and remarks on individual entries will be shown after the completion and successful declaration of results.",
      "Rule 18: In case of any dispute with regards to the team and competition’s rules and regulations, the decision taken by the organizers will be final and binding.",
    ],
    regdate: "26 Jan",
    organizers1: "Kamal Meena",
    organizers1Photo: "img/clubpics/Radhe.jpg",
    organizers2: "Kumar Shantanu",
    organizers2Photo: "img/cultpics/Shantanu.jpg",
  },
  {
    img: "img/eventpics/Copy of ANTAKSHARI (30 x 36 in).png",
    registerUrl: "https://forms.gle/HoMyDGufv49zJR829",
    title: "Antakshari Music Battle",
    description:
      "Antakshari Extravaganza: Immerse yourself in the rhythmic symphony of our fest! Join the lively musical showdown, where participants connect tunes seamlessly, creating an atmosphere of joy and camaraderie. An unmissable fusion of fun and music awaits you at this vibrant event!",
    startDate: "26 Jan",
    endDate: "30 Jan",
    rules: [
      "Rule 1: Participants are required to form a team of 3 and should also have a team name.",
      "Rule 2: Team name must be changed if the committee requests the participants to do so, or the participation will be nullified.",
      "Rule 3: This will be an intra-institute event; all the participants must be students of IIITV-ICD.",
      "Rule 4: This battle will be conducted in two rounds. Round 1 will be classic antakshari, and round 2 will be theme-based antakshari.",
      "Rule 5: Only Hindi songs can be sung by the teams while battling with other teams.",
      "Rule 6: Teams' performances will be judged on fluency in the lyrics of the song sung.",
      "Rule 7: The song must be sung for a minimum of 60 seconds.",
      "Rule 8: As technical musical expertise is not required, the organizers will act as judges to evaluate the performances of each team.",
      "Rule 9: Certain themes and marking schemes will be introduced as the battle progresses further.",
      "Rule 10: In case of any dispute regarding the team and the battle's rules and regulations, the decision taken by the organizers will be final and binding.",
    ],
    regdate: "26 Jan",
    organizers1: "Naveen",
    organizers1Photo: "img/clubpics/Naveen.png",
    organizers2: "Omni Manvani",
    organizers2Photo: "img/cultpics/Omni.jpg",
  },
  {
    img: "img/eventpics/Manch Mantra (30 x 36 in).png",
    registerUrl: "https://forms.gle/CgGaWP9d7r6o349UA",
    title: "Manch mantra",
    description:
      "Dive into the cinematic enchantment at the Manch Mantra event in Stavya! Each team embarks on a thrilling journey as they receive a movie to revolutionize—transforming its script and have to act upon. Unleash your creativity, rewrite the script, and take center stage to perform the ultimate, personalized movie magic! ",
    startDate: "27 Jan",
    endDate: "29 Jan",
    rules: [
      "Rule 1: Each team will receive a pre-selected movie name. Teams will have a time limit to recreate a scene or storyline from the movie through a live performance.",

      "Rule 2: Ensure the script and drama should not disrespect any culture/identity.",

      "Rule 3: By participating, the participant agrees that his/her work can be posted on Essence Club's & Eloquence Drama Club's Instagram handle.",

      "Rule 4: In case of any dispute concerning the team and the competition’s rules and regulations, the decision taken by the organizers will be final and binding.",
    ],
    regdate: "26 Jan",
    organizers1: "Kumar Shantanu",
    organizers1Photo: "img/cultpics/Shantanu.jpg",
    organizers2: "Suryansh Singh Raghuvansh",
    organizers2Photo: "img/cultpics/Suryansh.png",
  },
  {
    img: "img/eventpics/Copy of SHASHWAT (30 x 36 in).png",
    registerUrl: "https://forms.gle/CgGaWP9d7r6o349UA",
    title: "Shashwat Mythology Quiz",
    description:
    "Immerse yourself in the fascinating world of mythology with the Shashwat quiz event! Unleash your knowledge of ancient tales, gods, and legendary creatures. Engage in a thrilling competition that explores the rich tapestry of myths from diverse cultures. Join us for an epic journey into the realms of lore and legends at Shashwat's Mythology Quiz!",
    startDate: "27 Jan",
    endDate: "29 Jan",
    rules: [
      "Rule 1: It is a two-round offline event for the students of IIITV-ICD.",
      "Rule 2: Participants will have to register as a team of two through the circulated Google form. (Only one person needs to fill out the form).",
      "Rule 3: Rules for the respective rounds will be told before the commencement of that round.",
      "Rule 4: Winners will be decided based on the score of the quiz.",
      "Rule 5: If a participant’s action raises suspicion for the organizers, their candidature can be questioned. The organizers can take such decisions to ensure a fair competition.",
    ],
    regdate: "26 Jan",
    organizers1: "Harshit Soni",
    organizers1Photo: "img/clubpics/HarshitSoni.jpg",
    organizers2: "Devrikh Jatav",
    organizers2Photo: "img/litpics/DevrikhJatav.jpg",
  },
  {
    img: "img/eventpics/confero (30 x 36 in).png",
    registerUrl: "https://forms.gle/yNa96CtVjTLCy8mY6",
    title: "Confero : Debate Competition",
    description:
      "This event is structured to be held in 2 rounds, in each round every team will be assigned topic(s) and motions to debate on. In 1st round each team will be given only one motion, either for or against but in round 2 each team will be given both motions one by one on different topics .There will be predefined judging criteria on the basis of which final winnerswill be chosen.",
    startDate: "26 Jan",
    endDate: "27 Jan",
    rules: [
      "Rule 1: It will be a two-round debate competition.",
      "Rule 2: Participants will register through a Google form, which will be circulated a few days before the start of the event.",
      "Rule 3: The top 6 teams of round 1 will compete in the final round.",
      "Rule 4: In case of any discrepancy, the decision of the organizers will be final and binding.",
    ],
    regdate: "26 Jan",
    organizers1: "Rituraj Kumar",
    organizers1Photo: "img/clubpics/Rituraj.jpg",
    organizers2: "Anay Kumar Pandey",
    organizers2Photo: "img/litpics/AnayKumarPandey.png",
  },
  {
    img: "img/eventpics/avlekha.png",
    registerUrl: "https://forms.gle/e1fhE9wMtq3T1AwW9",
    title: "Avlekha : Hindi Poetry Writing Competition",
    description:
      "Avlekha invites participants to immerse themselves in the art of Hindi poetry in this inter-institute online event. Craft verses on themes revealed during the competition, showcasing your poetic prowess. Join us for an enriching experience where creativity and expression converge in the world of Hindi poetry, vying for recognition and excellence.",
    startDate: "26 Jan",
    endDate: "2 Feb",
    rules: [
      "Rule 1: This event will be conducted in hybrid mode.",
      "Rule 2: Topics will be declared on 26th January 2024.",
      "Rule 3: Students of IIITV-ICD will have to give offline submission of their composition.",
      "Rule 4: Students from other Institute/College/University will give online submission on Google forms.",
      "Rule 5: Plagiarism is strictly prohibited and can lead to disqualification of the participant.",
      "Rule 6: In case of any discrepancy, the decision of the organizers will be final and binding.",
    ],
    regdate: "26 Jan",
    organizers1: "Srijan sharma",
    organizers1Photo: "img/litpics/Srijan.jpg",
    organizers2: "Devrikh Jatav",
    organizers2Photo: "img/litpics/DevrikhJatav.jpg",
  },
  {
    img: "img/eventpics/inkint.png",
    registerUrl: "https://forms.gle/XVQ341hYTceSCr8YA",
    title: "Inkit : English Poetry Writing Competition",
    description:
      "Join 'Inkit,' the inter-institute online English poetry event, where participants showcase their poetic prowess. Express your creativity by crafting poems on themes unveiled during the event. A platform for literary excellence awaits, as wordsmiths compete to weave their verses and claim poetic glory.",
    startDate: "26 Jan",
    endDate: "2 Feb",
    rules: [
      "Rule 1: This event will be conducted in hybrid mode.",
      "Rule 2: Topics will be declared on 26th January 2023.",
      "Rule 3: Students of IIITV-ICD will have to give offline submission of their composition.",
      "Rule 4: Students from other Institute/College/University will give online submission on Google forms.",
      "Rule 5: Plagiarism is strictly prohibited and can lead to disqualification of the participant.",
      "Rule 6: In case of any discrepancy, the decision of the organizers will be final and binding.",
    ],
    regdate: "26 Jan",
    organizers1: "Srijan sharma",
    organizers1Photo: "img/litpics/Srijan.jpg",
    organizers2: "Devrikh Jatav",
    organizers2Photo: "img/litpics/DevrikhJatav.jpg",
  },
  {
    img: "img/eventpics/OPEN MIC (30 x 36 in).png",
    registerUrl: "https://forms.gle/AnzDwvKGoGWSQCTeA",
    title: "Open Mic",
    description:
      "A dynamic event where performers of all stripes showcase their talent in an intimate, unfiltered setting. From poetry and music to stand-up comedy, it's a platform where creativity takes the stage, fostering community and celebrating diverse expressions in a welcoming atmosphere.",
    startDate: "1 Feb",
    rules: [
      "Rule 1: It will be an open stage for all the students of IIITV-ICD.",
      "Rule 2: Each performer will be given 5 minutes (subject to change) to conclude their act.",
      "Rule 3: Religious and anti-social comments are strictly discouraged.",
      "Rule 4: Negative remarks and offensive comments are strictly prohibited.",
      "Rule 5: Event timings and venue will be circulated later.",
      "Rule 6: In case of any discrepancy, the decision of the organizers will be final and binding.",
    ],
    regdate: "26 Jan",
  },
  {
    img: "img/eventpics/ALTER EGO (30 x 36 in).png",
    registerUrl: "https://forms.gle/7PvWLmomBB5LFVdA7",
    title: "Alter Ego - Group Discussion",
    description:
      "It will be a single round competition. There will be three individuals in each clash. Each individual will be given a personality/role and he will have to defend that personality from rival’s allegations and attack them with his allegations. Each clash will be of 15 minutes and each individual will get 5 minutes to put his points.",
    startDate: "30 Jan",
    rules: [
      "Rule 1: Religious and anti-social comments are strictly discouraged.",
      "Rule 2: Negative remarks and offensive comments are strictly prohibited.",
      "Rule 3: Participants will register through a Google form, which will be circulated a few days before the start of the event.",
      "Rule 4: This will be an individual event where participants will be given a topic to have an open group discussion.",
      "Rule 5: In case of any discrepancy, the decision of the organizers will be final and binding.",
    ],
    regdate: "26 Jan",
  },
  {
    img: "img/eventpics/Copy of Bollywood Quiz (30 x 36 in).png",
    registerUrl: "https://forms.gle/PKhc9gq1zSgPWagR7",
    title: "Shabd Sangam Poetry Recitation",
    description:
      'Poets and Shayars are invited to "Shabdsangam," a poetic extravaganza where teams of 3 showcase their best works. Participants engage in Shayari and Poem rounds, with a unique twist—teams must craft verses on given words. Teams must come prepared with their best poem, adding an extra layer of competition and creativity to this celebration of literary prowess.',
    startDate: "29 Jan",
    rules: [
      "Rule 1: This event will be conducted in Offline mode.",
      "Rule 2: Topics will be declared on the spot.",
      "Rule 3: Participants will have to register as a team of three through the circulated Google form. (Only one person needs to fill out the form).",
      "Rule 4: The team will write the poem and recite on the spot.",
      "Rule 5: Plagiarism is strictly prohibited and can lead to disqualification of the participant.",
      "Rule 6: In case of any discrepancy, the decision of the organizers will be final and binding.",
    ],
    regdate: "26 Jan",
    organizers1: "Srijan sharma",
    organizers1Photo: "img/litpics/Srijan.jpg",
    organizers2: "Devrikh Jatav",
    organizers2Photo: "img/litpics/DevrikhJatav.jpg",
  },
  {
    img: "img/eventpics/disco night (30 x 36 in) (1).png",
    registerUrl: "https://youtu.be/dQw4w9WgXcQ",
    title: "Disco Night",
    description:
      "Cap off the enchanting Stavya- the Cultural Literature Fest with a dazzling Disco Night! Celebrate the fusion of literature and groove as we dance into the night, concluding this literary journey with rhythm, joy, and unforgettable memories.",
    startDate: "2 Feb",
    rules: [],
    regdate: "26 Jan",
  },
];
