export const EventsDB = [
        {
            img:"/src/assets/img/eventpics/SHASHWAT.png",
            registerUrl:"https://www.google.com",
            title:"Art Competition",
            description: "Nrityakala, an immersive dance celebration, invites you to experience the artistry of diverse movements, cultural narratives, and rhythmic expressions. Join the passionate dancers as they weave stories through the elegant choreography. And celebrating tradition and innovation in a captivating dance extravaganza.",
            startDate:"26 Jan",
            endDate:"2 Feb",
        },
        {
            img:"/src/assets/img/eventpics/SHASHWAT.png",
            registerUrl:"https://www.google.com",
            title:"Digital Cartooning",
            description: "Nrityakala, an immersive dance celebration, invites you to experience the artistry of diverse movements, cultural narratives, and rhythmic expressions. Join the passionate dancers as they weave stories through the elegant choreography. And celebrating tradition and innovation in a captivating dance extravaganza.",
            startDate:"26 Jan",
            endDate:"2 Feb",
        },
        {
            img:"/src/assets/img/eventpics/SHASHWAT.png",
            registerUrl:"https://www.google.com",
            title:"What If (Group Skit)",
            description: "Nrityakala, an immersive dance celebration, invites you to experience the artistry of diverse movements, cultural narratives, and rhythmic expressions. Join the passionate dancers as they weave stories through the elegant choreography. And celebrating tradition and innovation in a captivating dance extravaganza.",
            startDate:"27 Jan",
            endDate:"31 Jan",
        },
        {
            img:"/src/assets/img/eventpics/SHASHWAT.png",
            registerUrl:"https://www.google.com",
            title:"Bollywood Quiz",
            description: "Nrityakala, an immersive dance celebration, invites you to experience the artistry of diverse movements, cultural narratives, and rhythmic expressions. Join the passionate dancers as they weave stories through the elegant choreography. And celebrating tradition and innovation in a captivating dance extravaganza.",
            startDate:"27 Jan",
            endDate:"28 Jan",
        },
        {
            img:"/src/assets/img/eventpics/SHASHWAT.png",
            registerUrl:"https://www.google.com",
            title:"Nrityakala",
            description: "Nrityakala, an immersive dance celebration, invites you to experience the artistry of diverse movements, cultural narratives, and rhythmic expressions. Join the passionate dancers as they weave stories through the elegant choreography. And celebrating tradition and innovation in a captivating dance extravaganza.",
            startDate:"28 Jan",
          
        },
        {
            img:"/src/assets/img/eventpics/SHASHWAT.png",
            registerUrl:"https://www.google.com",
            title:"Photography contest",
            description: "Nrityakala, an immersive dance celebration, invites you to experience the artistry of diverse movements, cultural narratives, and rhythmic expressions. Join the passionate dancers as they weave stories through the elegant choreography. And celebrating tradition and innovation in a captivating dance extravaganza.",
            startDate:"26 Jan",
            endDate:"2 Feb",
        },
        {
            img:"/src/assets/img/eventpics/SHASHWAT.png",
            registerUrl:"https://www.google.com",
            title:"Antakshari Music Battle",
            description: "Nrityakala, an immersive dance celebration, invites you to experience the artistry of diverse movements, cultural narratives, and rhythmic expressions. Join the passionate dancers as they weave stories through the elegant choreography. And celebrating tradition and innovation in a captivating dance extravaganza.",
            startDate:"26 Jan",
            endDate:"30 Jan",
        },
        {
            img:"/src/assets/img/eventpics/SHASHWAT.png",
            registerUrl:"https://forms.gle/CgGaWP9d7r6o349UA",
            title:"Shashwat Mythology Quiz",
            description: "Nrityakala, an immersive dance celebration, invites you to experience the artistry of diverse movements, cultural narratives, and rhythmic expressions. Join the passionate dancers as they weave stories through the elegant choreography. And celebrating tradition and innovation in a captivating dance extravaganza.",
            startDate:"27 Jan",
            endDate:"29 Jan",
        },
        {
            img:"/src/assets/img/eventpics/SHASHWAT.png",
            registerUrl:"https://forms.gle/yNa96CtVjTLCy8mY6",
            title:"Confero : Debate Competition",
            description: "Nrityakala, an immersive dance celebration, invites you to experience the artistry of diverse movements, cultural narratives, and rhythmic expressions. Join the passionate dancers as they weave stories through the elegant choreography. And celebrating tradition and innovation in a captivating dance extravaganza.",
            startDate:"26 Jan",
            endDate:"27 Jan",
        },
        {
            img:"/src/assets/img/eventpics/SHASHWAT.png",
            registerUrl:"https://forms.gle/e1fhE9wMtq3T1AwW9",
            title:"Avlekha : Hindi Poetry Writing Competition",
            description: "Nrityakala, an immersive dance celebration, invites you to experience the artistry of diverse movements, cultural narratives, and rhythmic expressions. Join the passionate dancers as they weave stories through the elegant choreography. And celebrating tradition and innovation in a captivating dance extravaganza.",
            startDate:"26 Jan",
            endDate:"2 Feb",
        },
        {
            img:"/src/assets/img/eventpics/SHASHWAT.png",
            registerUrl:"https://forms.gle/XVQ341hYTceSCr8YA",
            title:"Inkit : English Poetry Writing Competition",
            description: "Nrityakala, an immersive dance celebration, invites you to experience the artistry of diverse movements, cultural narratives, and rhythmic expressions. Join the passionate dancers as they weave stories through the elegant choreography. And celebrating tradition and innovation in a captivating dance extravaganza.",
            startDate:"26 Jan",
            endDate:"2 Feb",
        },
        {
            img:"/src/assets/img/eventpics/SHASHWAT.png",
            registerUrl:"https://forms.gle/AnzDwvKGoGWSQCTeA",
            title:"Open Mic",
            description: "Nrityakala, an immersive dance celebration, invites you to experience the artistry of diverse movements, cultural narratives, and rhythmic expressions. Join the passionate dancers as they weave stories through the elegant choreography. And celebrating tradition and innovation in a captivating dance extravaganza.",
            startDate:"1 Feb",
            
        },
        {
            img:"/src/assets/img/eventpics/SHASHWAT.png",
            registerUrl:"https://forms.gle/7PvWLmomBB5LFVdA7",
            title:"Alter Ego - Group Discussion",
            description: "Nrityakala, an immersive dance celebration, invites you to experience the artistry of diverse movements, cultural narratives, and rhythmic expressions. Join the passionate dancers as they weave stories through the elegant choreography. And celebrating tradition and innovation in a captivating dance extravaganza.",
            startDate:"30 Jan",

        },
        {
            img:"/src/assets/img/eventpics/SHASHWAT.png",
            registerUrl:"https://forms.gle/PKhc9gq1zSgPWagR7",
            title:"Shabd Sangam Poetry Recitation",
            description: "Nrityakala, an immersive dance celebration, invites you to experience the artistry of diverse movements, cultural narratives, and rhythmic expressions. Join the passionate dancers as they weave stories through the elegant choreography. And celebrating tradition and innovation in a captivating dance extravaganza.",
            startDate:"29 Jan",

        },
        {
            img:"/src/assets/img/eventpics/SHASHWAT.png",
            registerUrl:"https://www.google.com",
            title:"Disco Night",
            description: "Nrityakala, an immersive dance celebration, invites you to experience the artistry of diverse movements, cultural narratives, and rhythmic expressions. Join the passionate dancers as they weave stories through the elegant choreography. And celebrating tradition and innovation in a captivating dance extravaganza.",
            startDate:"2 Feb",

        },
       
    ]